# Generated by Django 5.2.9 on 2025-12-18 04:40

from django.db import migrations
from django.db.models import Count

def remove_duplicates(apps, schema_editor):
    MyModel = apps.get_model('testApp', "Employee")

    duplicates = MyModel.objects.values('eno').annotate(c=Count('id')).filter(c__gt=1)

    for d in duplicates:
        objs = MyModel.objects.filter(eno=d['eno'])
        objs.exclude(id=objs.first().id).delete()

                        

class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates)
    ]
