# Generated by Django 5.2.9 on 2025-12-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_fix_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eno',
            field=models.IntegerField(unique=True),
        ),
    ]
