# Generated by Django 5.2.9 on 2025-12-20 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_alter_employee_eno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='emp_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eaddr',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eno',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esal',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(default='test@gmail.com', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
