# Generated by Django 5.2.9 on 2025-12-23 05:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
        ('testApp', '0004_rename_ename_employee_emp_name_remove_employee_eaddr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Department.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
