# Generated by Django 5.2.9 on 2025-12-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_employee_department_alter_employee_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(blank=True, max_length=65, null=True)),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='testApp.employee')),
            ],
        ),
    ]
