# Generated by Django 5.2.9 on 2025-12-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_employeeprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
