# Generated by Django 5.2.9 on 2025-12-25 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_alter_employeeprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('JR', 'Junior'), ('MID', 'Mid'), ('SR', 'Senior')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='testApp.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testApp.employeerole'),
        ),
    ]
