# Generated by Django 5.2.9 on 2025-12-25 12:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_employeerole_alter_employeeprofile_employee_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeerole',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('level'), name='unique_role_title_level'),
        ),
    ]
