# Generated by Django 5.2.9 on 2025-12-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_employeerole_unique_role_title_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerole',
            name='level',
            field=models.CharField(choices=[('JR', 'Junior'), ('MID', 'Mid'), ('SR', 'Senior'), ('INTERN', 'Intern')], max_length=10),
        ),
    ]
