# Generated by Django 5.2.9 on 2025-12-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0013_alter_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=7000),
        ),
    ]
