# Generated by Django 5.2.9 on 2025-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testApp', '0013_alter_employee_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_Active', models.BooleanField()),
                ('asignee', models.ManyToManyField(related_name='projects', to='testApp.employee')),
            ],
        ),
    ]
